# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('article_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
