# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160528_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rule',
            new_name='article',
        ),
    ]
